# Generated by Django 2.0.6 on 2018-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=26)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=26)),
                ('mysingle', models.CharField(max_length=20)),
            ],
        ),
    ]
