# Generated by Django 2.0.6 on 2018-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20180817_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('problem_input', models.FileField(upload_to='')),
                ('problems_output', models.FileField(upload_to='documents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
